// <auto-generated />
using System;
using EventEae1._2_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventEae1._2_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512183349_InitialTableCreation")]
    partial class InitialTableCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEae1._2_Backend.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CanApproveManagers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CanManageUsers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CanManageSettings"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CanCreateEvents"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CanViewOwnEvents"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CanViewTicketSales"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CanBrowseEvents"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CanViewOwnTickets"
                        },
                        new
                        {
                            Id = 9,
                            Name = "CanManageProfile"
                        });
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.RolePermission", b =>
                {
                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Role", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Role = "Admin",
                            PermissionId = 1,
                            Id = 1
                        },
                        new
                        {
                            Role = "Admin",
                            PermissionId = 2,
                            Id = 2
                        },
                        new
                        {
                            Role = "Admin",
                            PermissionId = 3,
                            Id = 3
                        },
                        new
                        {
                            Role = "Admin",
                            PermissionId = 9,
                            Id = 4
                        },
                        new
                        {
                            Role = "Manager",
                            PermissionId = 4,
                            Id = 5
                        },
                        new
                        {
                            Role = "Manager",
                            PermissionId = 5,
                            Id = 6
                        },
                        new
                        {
                            Role = "Manager",
                            PermissionId = 6,
                            Id = 7
                        },
                        new
                        {
                            Role = "Manager",
                            PermissionId = 9,
                            Id = 8
                        },
                        new
                        {
                            Role = "client",
                            PermissionId = 7,
                            Id = 9
                        },
                        new
                        {
                            Role = "client",
                            PermissionId = 8,
                            Id = 10
                        },
                        new
                        {
                            Role = "client",
                            PermissionId = 9,
                            Id = 11
                        });
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.TicketSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("TicketSales");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InitialStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.Event", b =>
                {
                    b.HasOne("EventEae1._2_Backend.Models.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.RolePermission", b =>
                {
                    b.HasOne("EventEae1._2_Backend.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.TicketSale", b =>
                {
                    b.HasOne("EventEae1._2_Backend.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventEae1._2_Backend.Models.Event", "Event")
                        .WithMany("TicketSales")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventEae1._2_Backend.Models.TicketType", "TicketType")
                        .WithMany("TicketSales")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Event");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.TicketType", b =>
                {
                    b.HasOne("EventEae1._2_Backend.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.UserPermission", b =>
                {
                    b.HasOne("EventEae1._2_Backend.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventEae1._2_Backend.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.Event", b =>
                {
                    b.Navigation("TicketSales");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.TicketType", b =>
                {
                    b.Navigation("TicketSales");
                });

            modelBuilder.Entity("EventEae1._2_Backend.Models.User", b =>
                {
                    b.Navigation("OrganizedEvents");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
